export type Game = { title: string; url: string; category: string }

// Each game: [title, embedUrl, category]
// Categories: editors-choice, html, arcade, car, bike, multiplayer, io, od (older devices), atari, clc (clicker), horror
const raw: [string, string, string][] = [
  // Editor's Choice (add your favorites here!)
  ["Eaglercraft (Minecraft) 1.12", "https://client.eaglercraft.win/eagler-files/wasm/1.12/Main/index.html", "editors-choice"],
  ["Eaglercraft (Minecraft) 1.8.9", "https://client.eaglercraft.win/eagler-files/wasm/1.8/AstraClient/index.html", "editors-choice"],
  ["GTA Vice City", "https://selenite1.freetls.fastly.net/resources/semag/gtavc/index.html", "editors-choice"],

  // HTML Games
  ["Highway Cars", "https://www.onlinegames.io/games/2023/construct/211/highway-cars/index.html", "html"],
  ["Moto X3M Winter", "https://unblocked-games.s3.amazonaws.com/moto-x3m-winter.html", "html"],
  ["Crazy MX", "https://www.crazygames.com/embed/crazy-mx", "html"],
  ["Sky Car Drift", "https://www.crazygames.com/embed/sky-car-drift", "html"],
  ["Moto Racing Club", "https://www.crazygames.com/embed/moto-racing-club", "html"],
  ["Bike Stunts 3D", "https://www.crazygames.com/embed/bike-stunts-3d", "html"],
  ["Parking Fury 3D", "https://www.crazygames.com/embed/parking-fury-3d", "html"],
  ["Rally Racer Dirt", "https://www.crazygames.com/embed/rally-racer-dirt", "html"],
  ["Demolition Derby 2", "https://www.crazygames.com/embed/demolition-derby-2", "html"],
  ["Stunt Paradise", "https://www.crazygames.com/embed/stunt-paradise", "html"],
  ["Super Bike Champion", "https://www.crazygames.com/embed/super-bike-champion", "html"],
  ["Traffic Rider", "https://www.crazygames.com/embed/traffic-rider", "html"],
  ["Narrow One", "https://www.crazygames.com/embed/narrow-one", "html"],
  ["Rocket Bot Royale", "https://www.crazygames.com/embed/rocket-bot-royale", "html"],
  ["Smash Karts", "https://www.crazygames.com/embed/smash-karts", "html"],
  ["Shell Shockers", "https://www.crazygames.com/embed/shell-shockers", "html"],
  ["Vortex 9", "https://www.crazygames.com/embed/vortex-9", "html"],
  ["Paper.io", "https://www.crazygames.com/embed/paper-io", "html"],
  ["Slither.io", "https://www.crazygames.com/embed/slither-io", "html"],
  ["Agar.io", "https://www.crazygames.com/embed/agar-io", "html"],
  ["Diep.io", "https://www.crazygames.com/embed/diep-io", "html"],
  ["Mope.io", "https://www.crazygames.com/embed/mope-io", "html"],
  ["Build Royale", "https://www.crazygames.com/embed/build-royale", "html"],
  ["Zombs Royale", "https://www.crazygames.com/embed/zombs-royale", "html"],
  ["Evowars.io", "https://www.crazygames.com/embed/evowars-io", "html"],
  ["Worms Zone", "https://www.crazygames.com/embed/worms-zone", "html"],
  ["Little Big Snake", "https://www.crazygames.com/embed/little-big-snake", "html"],
  ["Lordz.io", "https://www.crazygames.com/embed/lordz-io", "html"],
  ["Gulper.io", "https://www.crazygames.com/embed/gulper-io", "html"],
  ["Paper.io 2", "https://www.crazygames.com/embed/paper-io-2", "html"],
  ["Stumble Guys", "https://www.crazygames.com/embed/stumble-guys", "html"],
  ["Fall Boys", "https://www.crazygames.com/embed/fall-boys", "html"],
  ["Cookie Clicker", "https://orteil.dashnet.org/cookieclicker/", "od"],
  ["Little Alchemy", "https://littlealchemy.com", "od"],
  ["World's Biggest Pac-Man", "https://worldsbiggestpacman.com", "od"],
  ["HexGL", "http://hexgl.bkcore.com/play/", "od"],
  ["Line Rider", "https://www.linerider.com", "od"],
  ["Asteroids", "https://www.freeasteroids.org", "arcade"],
  ["Space Invaders", "https://spaceinvaders.de", "arcade"],
  ["Pong", "https://www.ponggame.org", "arcade"],
  ["Breakout", "https://www.breakoutgame.org", "arcade"],
  ["Frogger", "https://www.frogger-game.com", "arcade"],
  ["Doodle Road", "https://www.crazygames.com/embed/doodle-road", "arcade"],
  ["Jelly Dash", "https://www.crazygames.com/embed/jelly-dash", "arcade"],
  ["Jump Guys", "https://www.crazygames.com/embed/jump-guys", "arcade"],
  ["Epic Ballz.io", "https://www.crazygames.com/embed/epicballz-io", "arcade"],
  ["Night City Racing", "https://www.crazygames.com/embed/night-city-racing", "car"],
  ["Highway Racer", "https://www.crazygames.com/embed/highway-racer", "car"],
  ["Racing Limits", "https://www.crazygames.com/embed/racing-limits", "car"],
  ["Parking Jam", "https://www.crazygames.com/embed/parking-jam", "car"],
  ["Truck Driving Simulator", "https://www.crazygames.com/embed/truck-driving-simulator", "car"],
  ["Vehicle Masters", "https://www.crazygames.com/embed/vehicle-masters", "car"],
  ["Bike Jump", "https://www.crazygames.com/embed/bike-jump", "bike"],
  ["Cycle Extreme", "https://www.crazygames.com/embed/cycle-extreme", "bike"],
  ["Bike Trial Forest", "https://www.crazygames.com/embed/bike-trial-forest", "bike"],
  ["Moto Maniac 3", "https://www.crazygames.com/embed/moto-maniac-3", "bike"],
  ["Moto Rider 3D", "https://www.crazygames.com/embed/moto-rider-3d", "bike"],
  ["Fury Bike Rider", "https://www.crazygames.com/embed/fury-bike-rider", "bike"],
  ["Stickman Moto Race", "https://www.crazygames.com/embed/stickman-moto-race", "bike"],
  ["Battledudes.io", "https://www.crazygames.com/embed/battledudesio", "multiplayer"],
  ["Chess Online MP", "https://www.crazygames.com/embed/chess-online-mp", "multiplayer"],
  ["8 Ball Pool MP", "https://www.crazygames.com/embed/8-ball-pool-mp", "multiplayer"],
  ["Connect 4 Online", "https://www.crazygames.com/embed/connect-4-online", "multiplayer"],
  ["Checkers Free", "https://www.crazygames.com/embed/checkers-free", "multiplayer"],
  ["Ninja Parkour MP", "https://www.crazygames.com/embed/ninja-parkour-mp", "multiplayer"],
  ["Escape Prison MP", "https://www.crazygames.com/embed/escape-prison-mp", "multiplayer"],
  ["Football Tricks", "https://www.crazygames.com/embed/football-tricks", "multiplayer"],
  ["Basketball Master", "https://www.crazygames.com/embed/basketball-master", "multiplayer"],
  ["Polytrack", "https://www.crazygames.com/embed/polytrack", "multiplayer"],
  ["Mini Golf Club", "https://www.crazygames.com/embed/mini-golf-club", "multiplayer"],
  ["Tanks 3D", "https://www.crazygames.com/embed/tanks-3d", "multiplayer"],
  ["Ships 3D", "https://www.crazygames.com/embed/ships-3d", "multiplayer"],
  ["Simply Prop Hunt", "https://www.crazygames.com/embed/simply-prop-hunt", "multiplayer"],
  ["Skillwarz", "https://www.crazygames.com/embed/skillwarz", "multiplayer"],
  ["Skribbl.io", "https://www.crazygames.com/embed/skribbl-io", "multiplayer"],
  ["Survev.io", "https://www.crazygames.com/embed/survev-io", "multiplayer"],
  ["War Brokers", "https://www.crazygames.com/embed/war-brokers", "multiplayer"],
  ["Warcall.io", "https://www.crazygames.com/embed/warcall-io", "multiplayer"],
  ["Taming.io", "https://www.crazygames.com/embed/taming-io", "multiplayer"],
  ["TheLast.io", "https://www.crazygames.com/embed/thelast-io", "multiplayer"],
  ["TileMan.io", "https://www.crazygames.com/embed/tileman-io", "multiplayer"],
  ["Tina Detective", "https://www.crazygames.com/embed/tina-detective", "multiplayer"],
  ["Traffic Cop 3D", "https://www.crazygames.com/embed/traffic-cop-3d", "multiplayer"],
  ["Wrong Way", "https://www.crazygames.com/embed/wrong-way", "multiplayer"],
  ["WorldGuessr", "https://www.crazygames.com/embed/worldguessr", "multiplayer"],
  ["Worm Hunt", "https://www.crazygames.com/embed/worm-hunt", "multiplayer"],
  ["Worms Zone", "https://www.crazygames.com/embed/worms-zone", "multiplayer"],
  ["Poxel.io", "https://www.crazygames.com/embed/poxel-io", "multiplayer"],
  ["Stabfish 2", "https://www.crazygames.com/embed/stabfish-2", "multiplayer"],
  ["Stabfish.io", "https://www.crazygames.com/embed/stabfish-io", "multiplayer"],
  ["Starblast", "https://www.crazygames.com/embed/starblast", "multiplayer"],
  ["Mazean", "https://www.crazygames.com/embed/mazean", "multiplayer"],
  ["Merge Construct", "https://www.crazygames.com/embed/merge-construct", "multiplayer"],
  ["Mine Craft.io", "https://www.crazygames.com/embed/mine-craftio", "multiplayer"],
  ["Mini Caps Arena", "https://www.crazygames.com/embed/mini-caps-arena", "multiplayer"],
  ["Miniblox", "https://www.crazygames.com/embed/miniblox", "multiplayer"],
  ["Mini Giants.io", "https://www.crazygames.com/embed/mini-giantsio", "multiplayer"],
  ["MK48.io", "https://www.crazygames.com/embed/mk48io", "multiplayer"],
  ["Monster Cars Simulator", "https://www.crazygames.com/embed/monster-cars-simulator", "multiplayer"],
  ["Dirt Bike Mad Skills", "https://www.crazygames.com/embed/dirt-bike-mad-skills", "multiplayer"],
  ["Doodle Road", "https://www.crazygames.com/embed/doodle-road", "multiplayer"],
  ["Draw Crash Race", "https://www.crazygames.com/embed/draw-crash-race", "multiplayer"],
  ["Doors Castle", "https://www.crazygames.com/embed/doors-castle", "multiplayer"],
  ["Downtown 1930s Mafia", "https://www.crazygames.com/embed/downtown-1930s-mafia", "multiplayer"],
  ["Dragon Vice City", "https://www.crazygames.com/embed/dragon-vice-city", "multiplayer"],
  ["Drift Boss", "https://www.crazygames.com/embed/drift-boss", "multiplayer"],
  ["Drift Hunters", "https://www.crazygames.com/embed/drift-hunters", "multiplayer"],
  ["Ducklings", "https://www.crazygames.com/embed/ducklings", "multiplayer"],
  ["Eggy Car", "https://www.crazygames.com/embed/eggy-car", "multiplayer"],
  ["EpicBallz.io", "https://www.crazygames.com/embed/epicballzio", "multiplayer"],
  ["Evolution Factor", "https://www.crazygames.com/embed/evolution-factor", "multiplayer"],
  ["EvoWars.io", "https://www.crazygames.com/embed/evowarsio", "multiplayer"],
  ["EvoWorld.io", "https://www.crazygames.com/embed/evoworldio", "multiplayer"],
  ["Fortzone Battle Royale", "https://www.crazygames.com/embed/fortzone-battle-royale", "multiplayer"],
  ["Four Colors Uno", "https://www.crazygames.com/embed/four-colors-uno", "multiplayer"],
  ["Free Rally Vice", "https://www.crazygames.com/embed/free-rally-vice", "multiplayer"],
  ["Free Rider", "https://www.crazygames.com/embed/free-rider", "multiplayer"],
  ["Free Rider 2", "https://www.crazygames.com/embed/free-rider-2", "multiplayer"],
  ["Frogger", "https://www.crazygames.com/embed/frogger", "multiplayer"],
  ["Frontwars.io", "https://www.crazygames.com/embed/frontwarsio", "multiplayer"],
  ["Fury Bike Rider", "https://www.crazygames.com/embed/fury-bike-rider", "multiplayer"],
  ["Gearshift One", "https://www.crazygames.com/embed/gearshift-one", "multiplayer"],
  ["GoBattle.io", "https://www.crazygames.com/embed/gobattleio", "multiplayer"],
  ["GoKarts.io", "https://www.crazygames.com/embed/gokartsio", "multiplayer"],
  ["Gold Rush Arena", "https://www.crazygames.com/embed/gold-rush-arena", "multiplayer"],
  ["Golf Mania", "https://www.crazygames.com/embed/golf-mania", "multiplayer"],
  ["Goober Dash", "https://www.crazygames.com/embed/goober-dash", "multiplayer"],
  ["Grand Action Simulator NY", "https://www.crazygames.com/embed/grand-action-simulator-ny", "multiplayer"],
  ["Grand Cyber City", "https://www.crazygames.com/embed/grand-cyber-city", "multiplayer"],
  ["Gridpunk 3v3", "https://www.crazygames.com/embed/gridpunk-3v3", "multiplayer"],
  ["GrowDen.io", "https://www.crazygames.com/embed/growdenio", "multiplayer"],
  ["GT Cars Mega Ramps", "https://www.crazygames.com/embed/gt-cars-mega-ramps", "multiplayer"],
  ["Hole.io", "https://www.crazygames.com/embed/holeyio", "multiplayer"],
  ["Hyper Cars Ramp Crash", "https://www.crazygames.com/embed/hyper-cars-ramp-crash", "multiplayer"],
  ["Jelly Dash", "https://www.crazygames.com/embed/jelly-dash", "multiplayer"],
  ["Jump Guys", "https://www.crazygames.com/embed/jump-guys", "multiplayer"],
  ["King.io World War", "https://www.crazygames.com/embed/kingio-world-war", "multiplayer"],
  ["Kiomet", "https://www.crazygames.com/embed/kiomet", "multiplayer"],
  ["Kirka.io", "https://www.crazygames.com/embed/kirkaio", "multiplayer"],
  ["Kour.io", "https://www.crazygames.com/embed/kourio", "multiplayer"],
  ["Little Alchemy", "https://littlealchemy.com", "od"],
  ["Line Rider", "https://www.linerider.com", "od"],
  ["Cookie Clicker", "https://orteil.dashnet.org/cookieclicker/", "od"],
  ["Breakout Classic", "https://www.breakoutgame.org", "atari"],
  ["Frogger Classic", "https://froggerclassic.appspot.com", "atari"],
  // Car Games
  ["Sky Riders", "https://www.crazygames.com/embed/sky-riders-buk", "car"],
  ["Smash Karts", "https://www.crazygames.com/embed/smash-karts", "car"],
  ["Racing Limits", "https://www.crazygames.com/embed/racing-limits", "car"],
  ["Sandbox City", "https://www.crazygames.com/embed/sandbox-city---cars-zombies-ragdolls", "car"],
  ["Night City Racing", "https://www.crazygames.com/embed/night-city-racing", "car"],
  ["Rally Racer Dirt", "https://www.crazygames.com/embed/rally-racer-dirt", "car"],
  ["Stunt Paradise", "https://www.crazygames.com/embed/stunt-paradise", "car"],
  ["Doodle Road", "https://www.crazygames.com/embed/doodle-road", "car"],
  ["Parking Jam", "https://www.crazygames.com/embed/parking-jam-dqq", "car"],
  ["Traffic Cop 3D", "https://www.crazygames.com/embed/traffic-cop-3d", "car"],
  ["Demolition Derby 3", "https://www.crazygames.com/embed/demolition-derby-3", "car"],
  ["Super Star Car", "https://www.crazygames.com/embed/super-star-car", "car"],
  ["PolyTrack", "https://www.crazygames.com/embed/polytrack", "car"],
  ["Evolution Factor", "https://www.crazygames.com/embed/evolution-factor-1", "car"],
  ["Draw Crash Race", "https://www.crazygames.com/embed/draw-crash-race", "car"],
  ["Assault Bots", "https://www.crazygames.com/embed/bot-machines", "car"],
  ["Drift Hunters", "https://www.crazygames.com/embed/drift-hunters", "car"],
  ["Offroad Island", "https://www.crazygames.com/embed/offroad-island", "car"],
  ["Mr. Racer", "https://www.crazygames.com/embed/mr-racer---car-racing", "car"],
  ["Boom Karts", "https://www.crazygames.com/embed/boom-karts", "car"],
  ["Super Crime Steel War Hero", "https://www.crazygames.com/embed/super-crime-steel-war-hero", "car"],
  ["Crazy Motorcycle", "https://www.crazygames.com/embed/crazy-motorcycle", "car"],
  ["Downtown 1930s Mafia", "https://www.crazygames.com/embed/downtown-1930s-mafia", "car"],
  ["Merge & Construct", "https://www.crazygames.com/embed/merge-construct", "car"],
  ["Ultimate Flying Car", "https://www.crazygames.com/embed/ultimate-flying-car", "car"],
  ["Gearshift One", "https://www.crazygames.com/embed/gearshift-one", "car"],
  ["GT Cars Mega Ramps", "https://www.crazygames.com/embed/gt-cars-mega-ramps", "car"],
  ["Xtreme City Drifting", "https://www.crazygames.com/embed/xtreme-city-drifting", "car"],
  ["Demolition Derby 2", "https://www.crazygames.com/embed/demolition-derby-2", "car"],
  ["Monster Cars Simulator", "https://www.crazygames.com/embed/monster-cars-ultimate-simulator", "car"],
  ["Grand Cyber City", "https://www.crazygames.com/embed/grand-cyber-city", "car"],
  ["Crazy Grand Prix", "https://www.crazygames.com/embed/crazy-grand-prix", "car"],
  ["City Car Driving Online", "https://www.crazygames.com/embed/city-car-driving-simulator-online", "car"],
  ["ATV Ultimate Offroad", "https://www.crazygames.com/embed/atv-ultimate-offroad", "car"],
  ["Truck Driving Simulator", "https://www.crazygames.com/embed/truck-driving-simulator-game", "car"],
  ["Mad Town Andreas", "https://www.crazygames.com/embed/mad-town-andreas-mafia-storie", "car"],
  ["Russian Car Driver ZIL", "https://www.crazygames.com/embed/russian-car-driver-zil-130", "car"],
  ["Racing Builder", "https://www.crazygames.com/embed/racing-builder", "car"],
  ["Drift Boss", "https://www.crazygames.com/embed/drift-boss", "car"],
  ["Parking Fury 3D", "https://www.crazygames.com/embed/parking-fury-3d-side-hustle", "car"],
  ["Derby Crash 4", "https://www.crazygames.com/embed/derby-crash-4", "car"],
  ["Grand Action Simulator NY", "https://www.crazygames.com/embed/grand-action-simulator-new-york-car-gang", "car"],
  ["Ultimate Flying Car 2", "https://www.crazygames.com/embed/ultimate-flying-car-2", "car"],
  ["Vehicle Masters", "https://www.crazygames.com/embed/vehicle-masters", "car"],
  ["Crazy Stunt Cars MP", "https://www.crazygames.com/embed/crazy-stunt-cars-multiplayer", "car"],
  ["4x4 Offroader", "https://www.crazygames.com/embed/4x4-offroader", "car"],
  ["Highway Racer", "https://www.crazygames.com/embed/highway-racer", "car"],
  ["Madalin Cars Multiplayer", "https://www.crazygames.com/embed/madalin-cars-multiplayer", "car"],
  ["Truck Simulator Russia", "https://www.crazygames.com/embed/truck-simulator-russia", "car"],
  ["Stunt Master", "https://www.crazygames.com/embed/city-car-driving-simulator-ultimate", "car"],
  ["Bouncy Motors", "https://www.crazygames.com/embed/bouncy-motors", "car"],
  ["Free Rally Vice", "https://www.crazygames.com/embed/free-rally-vice", "car"],
  ["Mini-Caps Arena", "https://www.crazygames.com/embed/mini-caps-arena", "car"],
  ["Hyper Cars Ramp Crash", "https://www.crazygames.com/embed/hyper-cars-ramp-crash", "car"],
  ["Rovercraft", "https://www.crazygames.com/embed/rovercraft", "car"],
  ["Derby Crash", "https://www.crazygames.com/embed/derbycrash", "car"],
  ["Madalin Stunt Cars 2", "https://www.crazygames.com/embed/madalin-stunt-cars-2", "car"],
  ["Wrong Way", "https://www.crazygames.com/embed/wrongway", "car"],
  ["Rush Hour", "https://www.crazygames.com/embed/rush-hour-owq", "car"],
  ["Eggy Car", "https://www.crazygames.com/embed/eggy-car", "car"],
  ["MX Offroad Master", "https://www.crazygames.com/embed/mx-offroad-master", "car"],
  // Bike Games
  ["Traffic Rider", "https://www.crazygames.com/embed/traffic-rider-vvq", "bike"],
  ["Super Bike Champion", "https://www.crazygames.com/embed/super-bike-the-champion", "bike"],
  ["Moto X3M CG", "https://www.crazygames.com/embed/moto-x3m", "bike"],
  ["Paper Boy Race", "https://www.crazygames.com/embed/paper-boy-race-running-game", "bike"],
  ["Riders Downhill Racing", "https://www.crazygames.com/embed/riders-downhill-racing", "bike"],
  ["Super MX Last Season", "https://www.crazygames.com/embed/super-mx-last-season", "bike"],
  ["Paper Delivery Boy", "https://www.crazygames.com/embed/paper-delivery-boy", "bike"],
  ["Moto X3M 5 Pool Party", "https://www.crazygames.com/embed/moto-x3m-pool-party", "bike"],
  ["Dragon Vice City", "https://www.crazygames.com/embed/dragon-vice-city", "bike"],
  ["Moto X3M 4 Winter", "https://www.crazygames.com/embed/moto-x3m-4", "bike"],
  ["Sunset Bike Racing", "https://www.crazygames.com/embed/sunset-bike-racing", "bike"],
  ["Trial Mania", "https://www.crazygames.com/embed/trial-mania", "bike"],
  ["Xtreme Moto Mayhem", "https://www.crazygames.com/embed/xtreme-moto-mayhem", "bike"],
  ["Moto X3M 6 Spooky Land", "https://www.crazygames.com/embed/moto-x3m-spooky-land", "bike"],
  ["GoKarts.io", "https://www.crazygames.com/embed/gokarts-io", "bike"],
  ["3D Moto Simulator 2", "https://www.crazygames.com/embed/3d-moto-simulator-2", "bike"],
  ["SCAR", "https://www.crazygames.com/embed/scar", "bike"],
  ["MotoCross Riders", "https://www.crazygames.com/embed/motocross-riders", "bike"],
  ["Super MX Champion", "https://www.crazygames.com/embed/super-mx-motocross-simulator", "bike"],
  ["Bike Jump", "https://www.crazygames.com/embed/bike-jump", "bike"],
  ["Airborne Motocross", "https://www.crazygames.com/embed/airborne-motocross", "bike"],
  ["Trial Bike Epic Stunts", "https://www.crazygames.com/embed/trial-bike-epic-stunts", "bike"],
  ["Ramp Bike Jumping", "https://www.crazygames.com/embed/ramp-bike-jumping", "bike"],
  ["Wheelie Up", "https://www.crazygames.com/embed/wheelie-up", "bike"],
  ["Dirt Bike Mad Skills", "https://www.crazygames.com/embed/dirt-bike-mad-skills", "bike"],
  ["Crazy Moto Stunts", "https://www.crazygames.com/embed/crazy-moto-stunts", "bike"],
  ["Moto Rider 3D", "https://www.crazygames.com/embed/moto-rider-3d", "bike"],
  ["Moto Racing Club", "https://www.crazygames.com/embed/moto-racing-club", "bike"],
  ["Hill Climb Moto Bike", "https://www.crazygames.com/embed/hill-climb-on-moto-bike", "bike"],
  ["Where's My Pizza?", "https://www.crazygames.com/embed/where-s-my-pizza", "bike"],
  ["Bike Stunts 3D", "https://www.crazygames.com/embed/bike-stunts-race-bike-games-3d", "bike"],
  ["Trials Ice Ride", "https://www.crazygames.com/embed/trail-ice-ride", "bike"],
  ["Blocky Trials", "https://www.crazygames.com/embed/blocky-trials", "bike"],
  ["Stunt Dirt Bike", "https://www.crazygames.com/embed/stunt-dirt-bike", "bike"],
  ["Cycle Extreme", "https://www.crazygames.com/embed/cycle-extreme", "bike"],
  ["Motocross Dirt Bike", "https://www.crazygames.com/embed/motocross-dirt-bike-race-games", "bike"],
  ["Trials Ride", "https://www.crazygames.com/embed/trials-ride", "bike"],
  ["Crazy MotoX MP", "https://www.crazygames.com/embed/crazy-motox-multiplayer", "bike"],
  ["Fury Bike Rider", "https://www.crazygames.com/embed/fury-bike-rider", "bike"],
  ["Super Fast Driver", "https://www.crazygames.com/embed/super-fast-driver", "bike"],
  ["Stunt Mania 3D", "https://www.crazygames.com/embed/stunt-mania-3d", "bike"],
  ["Free Rider", "https://www.crazygames.com/embed/free-rider", "bike"],
  ["Stickman Moto Race", "https://www.crazygames.com/embed/stickman-moto-race-extreme", "bike"],
  ["MotoGP Motocross Race", "https://www.crazygames.com/embed/motogp-motocross-race", "bike"],
  ["Crazy MX", "https://www.crazygames.com/embed/crazy-mx", "bike"],
  ["Moto Maniac 3", "https://www.crazygames.com/embed/moto-maniac-3", "bike"],
  ["Cartoon Moto Stunt", "https://www.crazygames.com/embed/cartoon-moto-stunt", "bike"],
  ["Night Rider", "https://www.crazygames.com/embed/night-rider", "bike"],
  ["Bike Trial Forest", "https://www.crazygames.com/embed/bike-trial-xtreme-forest", "bike"],
  ["Free Rider 2", "https://www.crazygames.com/embed/free-rider-2", "bike"],
  ["Stickman Zombie Motorcycle", "https://www.crazygames.com/embed/stickman-zombie-motorcycle", "bike"],
  ["Switch Wheel Race", "https://www.crazygames.com/embed/switch-wheel-race-master", "bike"],
  // Multiplayer Games
  ["Bloxd.io", "https://www.crazygames.com/embed/bloxdhop-io", "multiplayer"],
  ["Four Colors (Uno)", "https://www.crazygames.com/embed/uno-online", "multiplayer"],
  ["Fortzone Battle Royale", "https://www.crazygames.com/embed/fortzone-battle-royale-xkd", "multiplayer"],
  ["Miniblox", "https://www.crazygames.com/embed/miniblox", "multiplayer"],
  ["BuildNow GG", "https://www.crazygames.com/embed/buildnow-gg", "multiplayer"],
  ["Shell Shockers", "https://www.crazygames.com/embed/shellshockersio", "multiplayer"],
  ["SkillWarz", "https://www.crazygames.com/embed/skillwarz", "multiplayer"],
  ["EvoWars.io", "https://www.crazygames.com/embed/evowarsio", "multiplayer"],
  ["Squid Game Online", "https://www.crazygames.com/embed/squid-game-online", "multiplayer"],
  ["CubeRealm.io", "https://www.crazygames.com/embed/cuberealm-io", "multiplayer"],
  ["8 Ball Pool MP", "https://www.crazygames.com/embed/8-ball-pool-billiards-multiplayer", "multiplayer"],
  ["Escape From Pizzeria", "https://www.crazygames.com/embed/escape-from-pizzeria", "multiplayer"],
  ["Cowz.io", "https://www.crazygames.com/embed/cowz-io", "multiplayer"],
  ["Bank Heist", "https://www.crazygames.com/embed/bank-heist", "multiplayer"],
  ["Golf Mania", "https://www.crazygames.com/embed/golf-mania", "multiplayer"],
  ["Poxel.io", "https://www.crazygames.com/embed/poxel-io", "multiplayer"],
  ["Survev.io", "https://www.crazygames.com/embed/survev", "multiplayer"],
  ["Ships 3D", "https://www.crazygames.com/embed/ships-3d", "multiplayer"],
  ["Tanks 3D", "https://www.crazygames.com/embed/tanks-3d", "multiplayer"],
  ["Mini Golf Club", "https://www.crazygames.com/embed/mini-golf-club", "multiplayer"],
  ["Pixel Warfare", "https://www.crazygames.com/embed/pixel-warfare", "multiplayer"],
  ["Kour.io", "https://www.crazygames.com/embed/kour-io", "multiplayer"],
  ["BLOCOPS", "https://www.crazygames.com/embed/blocops", "multiplayer"],
  ["Escape Prison MP", "https://www.crazygames.com/embed/escape-from-prison-multiplayer", "multiplayer"],
  ["TileMan.io", "https://www.crazygames.com/embed/tileman-io", "multiplayer"],
  ["WorldGuessr", "https://www.crazygames.com/embed/worldguessr", "multiplayer"],
  ["Crazy Guys", "https://www.crazygames.com/embed/crazy-guys", "multiplayer"],
  ["Mk48.io", "https://www.crazygames.com/embed/mk48-io", "multiplayer"],
  ["Chess Free", "https://www.crazygames.com/embed/chess-free", "multiplayer"],
  ["Kiomet", "https://www.crazygames.com/embed/kiomet-com", "multiplayer"],
  ["Brainrots.io", "https://www.crazygames.com/embed/italianbrainrotquiz-io", "multiplayer"],
  ["Doors Castle", "https://www.crazygames.com/embed/doors-castle", "multiplayer"],
  ["Mancala Classic", "https://www.crazygames.com/embed/mancala-classic", "multiplayer"],
  ["Gridpunk 3v3", "https://www.crazygames.com/embed/gridpunk---3v3-battle-royale", "multiplayer"],
  ["Kirka.io", "https://www.crazygames.com/embed/kirka-io", "multiplayer"],
  ["Race Clicker", "https://www.crazygames.com/embed/race-clicker-tap-tap-game", "multiplayer"],
  ["Connect 4 Online", "https://www.crazygames.com/embed/4-in-a-row-connected-multiplayer-online", "multiplayer"],
  ["Checkers Free", "https://www.crazygames.com/embed/checkers-free", "multiplayer"],
  ["Mazean", "https://www.crazygames.com/embed/mazean-com", "multiplayer"],
  ["Struckd 3D Creator", "https://www.crazygames.com/embed/struckd---3d-game-creator", "multiplayer"],
  ["War Brokers", "https://www.crazygames.com/embed/war-brokers-io", "multiplayer"],
  ["Goober Dash", "https://www.crazygames.com/embed/goober-dash", "multiplayer"],
  ["Vortex 9", "https://www.crazygames.com/embed/vortex-9-ubs", "multiplayer"],
  ["Eternal Siege", "https://www.crazygames.com/embed/eternal-siege", "multiplayer"],
  ["Ninja Parkour MP", "https://www.crazygames.com/embed/ninja-parkour-multiplayer", "multiplayer"],
  ["Street Fighter Sim", "https://www.crazygames.com/embed/street-fighter-simulator", "multiplayer"],
  ["Jump Guys", "https://www.crazygames.com/embed/jump-guys", "multiplayer"],
  ["Chess Online MP", "https://www.crazygames.com/embed/chess-online-multiplayer-game", "multiplayer"],
  ["Krunker", "https://www.crazygames.com/embed/krunker-io", "multiplayer"],
  ["Hazmob FPS", "https://www.crazygames.com/embed/hazmob-fps-online-shooter", "multiplayer"],
  // IO Games
  ["Agar.io", "https://www.crazygames.com/embed/agario", "io"],
  ["Slither.io CG", "https://www.crazygames.com/embed/snake-io", "io"],
  ["Paper.io 2", "https://www.crazygames.com/embed/paper-io-2", "io"],
  ["Diep.io", "https://www.crazygames.com/embed/diepio", "io"],
  ["Mope.io", "https://www.crazygames.com/embed/mopeio", "io"],
  ["EvoWorld.io", "https://www.crazygames.com/embed/flyordieio", "io"],
  ["Taming.io", "https://www.crazygames.com/embed/taming-io", "io"],
  ["Voxiom.io", "https://www.crazygames.com/embed/voxiom-io", "io"],
  ["StarBlast", "https://www.crazygames.com/embed/starblastio", "io"],
  ["Holey.io", "https://www.crazygames.com/embed/holey-io-battle-royale", "io"],
  ["Cubes 2048.io", "https://www.crazygames.com/embed/cubes-2048-io", "io"],
  ["SimplyUp.io", "https://www.crazygames.com/embed/simplyup-io", "io"],
  ["Worms.Zone", "https://www.crazygames.com/embed/worms-zone", "io"],
  ["Gulper.io", "https://www.crazygames.com/embed/gulper-io", "io"],
  ["BattleDudes.io", "https://www.crazygames.com/embed/battledudes-io", "io"],
  ["Stabfish 2", "https://www.crazygames.com/embed/stabfish2-io-multiplayer", "io"],
  ["Worm Hunt", "https://www.crazygames.com/embed/worm-hunt", "io"],
  ["Little Big Snake", "https://www.crazygames.com/embed/little-big-snake-io", "io"],
  ["Lordz.io", "https://www.crazygames.com/embed/lordzio", "io"],
  ["MiniGiants.io", "https://www.crazygames.com/embed/minigiants-io", "io"],
  ["digdig.io", "https://www.crazygames.com/embed/digdig-io", "io"],
  ["Sploop.io", "https://www.crazygames.com/embed/sploop-io", "io"],
  ["WarCall.io", "https://www.crazygames.com/embed/warcall-io", "io"],
  ["Archer Clash", "https://www.crazygames.com/embed/archer-clash-ftj", "io"],
  ["BrutalMania.io", "https://www.crazygames.com/embed/brutalmania-io", "io"],
  ["EpicBallz.io", "https://www.crazygames.com/embed/epicballz-io", "io"],
  ["Skribbl.io", "https://www.crazygames.com/embed/skribblio", "io"],
  ["Stabfish.io", "https://www.crazygames.com/embed/stabfish-io", "io"],
  ["Tzared", "https://www.crazygames.com/embed/tzared", "io"],
  ["Mine-Craft.io", "https://www.crazygames.com/embed/mine-craft-io", "io"],
  ["Gold Rush Arena", "https://www.crazygames.com/embed/gold-rush-arena", "io"],
  ["Rocket Bot Royale", "https://www.crazygames.com/embed/rocket-bot-royale", "io"],
  ["STUG", "https://www.crazygames.com/embed/stug", "io"],
  ["Deadshot.io", "https://www.crazygames.com/embed/deadshot-io", "io"],
  ["1v1.lol", "https://www.crazygames.com/embed/1v1-lol", "io"],
  ["Build Royale", "https://www.crazygames.com/embed/buildroyale-io", "io"],
  ["Ducklings", "https://www.crazygames.com/embed/ducklings", "io"],
  ["Zombs Royale", "https://www.crazygames.com/embed/zombsroyaleio", "io"],
  ["LOL Beans", "https://www.crazygames.com/embed/lolbeans-io", "io"],
  ["Narrow One", "https://www.crazygames.com/embed/narrow-one", "io"],
  ["Bonk.io", "https://www.crazygames.com/embed/bonkio", "io"],
  ["FrontWars.io", "https://www.crazygames.com/embed/frontwars-io", "io"],
  ["Growden.io", "https://www.crazygames.com/embed/grow-a-garden---growden-io", "io"],
  ["Overtide.io", "https://www.crazygames.com/embed/overtide-io", "io"],
  ["GoBattle.io", "https://www.crazygames.com/embed/gobattleio", "io"],
  ["TheLast.io", "https://www.crazygames.com/embed/thelast-io", "io"],
  ["Raidfield 2", "https://www.crazygames.com/embed/raidfield-2-pjc", "io"],
  ["Noob Snake 2048", "https://www.crazygames.com/embed/noob-snake-2048", "io"],
  ["King.io World War", "https://www.crazygames.com/embed/king-io-world-war", "io"],
  ["Jelly Dash", "https://www.crazygames.com/embed/jelly-dash-uki", "io"],
  ["Simply Prop Hunt", "https://www.crazygames.com/embed/simply-prop-hunt", "io"],
  ["Bit Gun.io", "https://www.crazygames.com/embed/bit-gun-io", "io"],
  // Clicker Games
["Planet Clicker", "https://www.crazygames.com/game/planet-clicker", "clc"],
["Leek Factory Tycoon", "https://www.crazygames.com/game/leek-factory-tycoon", "clc"],
["Farm Ring Idle", "https://www.crazygames.com/game/farm-ring-idle", "clc"],
["Human Clicker Grow Organs", "https://www.crazygames.com/game/human-clicker-grow-organs", "clc"],
["Mister Mine", "https://www.crazygames.com/game/mister-mine", "clc"],
["Idle Mining Empire", "https://www.crazygames.com/game/idle-mining-empire", "clc"],
["Black Hole Idle", "https://www.crazygames.com/game/black-hole-idle", "clc"],
["Just One More Roll", "https://www.crazygames.com/game/just-one-more-roll", "clc"],
["Color Cannon Idle", "https://www.crazygames.com/game/color-cannon-idle", "clc"],
["When Civilians Dig Holes", "https://www.crazygames.com/game/when-civilians-dig-holes", "clc"],
["Babel Tower", "https://www.crazygames.com/game/babel-tower", "clc"],
["Plinky", "https://www.crazygames.com/game/plinky", "clc"],
["Evolutionary Tribe Mqd", "https://www.crazygames.com/game/evolutionary-tribe-mqd", "clc"],
["Cell To Singularity Mesozoic Valley", "https://www.crazygames.com/game/cell-to-singularity-mesozoic-valley", "clc"],
["Flywheel Incremental", "https://www.crazygames.com/game/flywheel-incremental", "clc"],
["Money Maker Bex", "https://www.crazygames.com/game/money-maker-bex", "clc"],
["Dualforce Idle", "https://www.crazygames.com/game/dualforce-idle", "clc"],
["Merge Miner", "https://www.crazygames.com/game/merge-miner", "clc"],
["Race Clicker Tap Tap Game", "https://www.crazygames.com/game/race-clicker-tap-tap-game", "clc"],
["Legend Of Fireball Mpp", "https://www.crazygames.com/game/legend-of-fireball-mpp", "clc"],
["Capybara Clicker", "https://www.crazygames.com/game/capybara-clicker", "clc"],
["Planet Destroy Idle", "https://www.crazygames.com/game/planet-destroy-idle", "clc"],
["Crusher Clicker", "https://www.crazygames.com/game/crusher-clicker", "clc"],
["Llama Legends", "https://www.crazygames.com/game/llama-legends", "clc"],
["Block Wall Destroyer", "https://www.crazygames.com/game/block-wall-destroyer", "clc"],
["Obby Vs Brainrot", "https://www.crazygames.com/game/obby-vs-brainrot", "clc"],
["Idle Football Manager", "https://www.crazygames.com/game/idle-football-manager", "clc"],
["Italian Brainrot Clicker Usp", "https://www.crazygames.com/game/italian-brainrot-clicker-usp", "clc"],
["Dominate All Shapes", "https://www.crazygames.com/game/dominate-all-shapes", "clc"],
["Planet Clicker 2", "https://www.crazygames.com/game/planet-clicker-2", "clc"],
["Circle Farm", "https://www.crazygames.com/game/circle-farm", "clc"],
["Merge Steal Brainrot", "https://www.crazygames.com/game/merge-steal-brainrot", "clc"],
["Grindcraft", "https://www.crazygames.com/game/grindcraft", "clc"],
["Omega Layers", "https://www.crazygames.com/game/omega-layers", "clc"],
["Incremental Epic Hero 2", "https://www.crazygames.com/game/incremental-epic-hero-2", "clc"],
["My Chicken Farm", "https://www.crazygames.com/game/my-chicken-farm", "clc"],
["Clicker Monsters Rpj", "https://www.crazygames.com/game/clicker-monsters-rpj", "clc"],
["Idle House Build", "https://www.crazygames.com/game/idle-house-build", "clc"],
["Capybara Clicker 2", "https://www.crazygames.com/game/capybara-clicker-2", "clc"],
["Evolve", "https://www.crazygames.com/game/evolve", "clc"],
["Block Clicker", "https://www.crazygames.com/game/block-clicker", "clc"],
["Mystery Digger", "https://www.crazygames.com/game/mystery-digger", "clc"],
["Mad Evolution Idle Merge", "https://www.crazygames.com/game/mad-evolution-idle-merge", "clc"],
["Simple Loot Idle", "https://www.crazygames.com/game/simple-loot-idle", "clc"],
["Commit Battery 3", "https://www.crazygames.com/game/commit-battery-3", "clc"],
["Metro Connect", "https://www.crazygames.com/game/metro-connect", "clc"],
["Neon Core Breaker", "https://www.crazygames.com/game/neon-core-breaker", "clc"],
["Emoji Clickers", "https://www.crazygames.com/game/emoji-clickers", "clc"],
["Farming Tycoon 3d Diu", "https://www.crazygames.com/game/farming-tycoon-3d-diu", "clc"],
["Clicker Heroes", "https://www.crazygames.com/game/clicker-heroes", "clc"],
["Street Life", "https://www.crazygames.com/game/street-life", "clc"],
["Gun Bounce Idle", "https://www.crazygames.com/game/gun-bounce-idle", "clc"],
["Plinko Clicker Hdl", "https://www.crazygames.com/game/plinko-clicker-hdl", "clc"],
["Corn Tycoon", "https://www.crazygames.com/game/corn-tycoon", "clc"],
["Pen Dig", "https://www.crazygames.com/game/pen-dig", "clc"],
["Idle Space Business Tycoon", "https://www.crazygames.com/game/idle-space-business-tycoon", "clc"],
["Money Factory Tycoon Idle Game", "https://www.crazygames.com/game/money-factory-tycoon-idle-game", "clc"],
["Ragdoll Drop Tycoon", "https://www.crazygames.com/game/ragdoll-drop-tycoon", "clc"],
["Planet Evolution Idle Clicker", "https://www.crazygames.com/game/planet-evolution-idle-clicker", "clc"],
["Merge A Fruit", "https://www.crazygames.com/game/merge-a-fruit", "clc"],
["Home Builder 3d", "https://www.crazygames.com/game/home-builder-3d", "clc"],
["Doge Miner", "https://www.crazygames.com/game/doge-miner", "clc"],
["Money Factory Aqs", "https://www.crazygames.com/game/money-factory-aqs", "clc"],
["Planet Life Idle", "https://www.crazygames.com/game/planet-life-idle", "clc"],
["Revolution Idle X Demo", "https://www.crazygames.com/game/revolution-idle-x-demo", "clc"],
["Idle Inventor", "https://www.crazygames.com/game/idle-inventor", "clc"],
  // Horror Games
  ["Horror Nights Story", "https://www.crazygames.com/game/horror-nights-story", "horror"],
  ["Slendrina Must Die The Forest", "https://www.crazygames.com/game/slendrina-must-die-the-forest", "horror"],
  ["Zombie Mayhem Online", "https://www.crazygames.com/game/zombie-mayhem-online", "horror"],
  ["Dr Psycho Hospital Escape", "https://www.crazygames.com/game/dr-psycho-hospital-escape", "horror"],
  ["Jeff The Killer Vs Slendrina", "https://www.crazygames.com/game/jeff-the-killer-vs-slendrina", "horror"],
  ["Slendrina Must Die The School", "https://www.crazygames.com/game/slendrina-must-die-the-school", "horror"],
  ["Evil Neighbor 2", "https://www.crazygames.com/game/evil-neighbor-2", "horror"],
  ["Slenderman Must Die", "https://www.crazygames.com/game/slenderman-must-die", "horror"],
  ["Dust A Post Apocalyptic Rpg", "https://www.crazygames.com/game/dust-a-post-apocalyptic-rpg", "horror"],
  ["Office Horror Story", "https://www.crazygames.com/game/office-horror-story", "horror"],
  ["Brother Wake Up", "https://www.crazygames.com/game/brother-wake-up", "horror"],
  ["Midnight Remastered", "https://www.crazygames.com/game/midnight-remastered", "horror"],
  ["Shoot Your Nightmare Space Isolation", "https://www.crazygames.com/game/shoot-your-nightmare-space-isolation", "horror"],
  ["Deep Space Horror Outpost", "https://www.crazygames.com/game/deep-space-horror-outpost", "horror"],
  ["Slenderman Must Die Sanatorium 2021", "https://www.crazygames.com/game/slenderman-must-die-sanatorium-2021", "horror"],
  ["Run Zombie Run", "https://www.crazygames.com/game/run-zombie-run", "horror"],
  ["Jeff The Killer Horrendous Smile", "https://www.crazygames.com/game/jeff-the-killer-horrendous-smile", "horror"],
  ["While We Sleep Slendrina Is Here", "https://www.crazygames.com/game/while-we-sleep-slendrina-is-here", "horror"],
  ["Shoot Your Nightmare Halloween", "https://www.crazygames.com/game/shoot-your-nightmare-halloween", "horror"],
  ["Nextdoor", "https://www.crazygames.com/game/nextdoor", "horror"],
  ["Horror Room Scary Hotel Tycoon", "https://www.crazygames.com/game/horror-room-scary-hotel-tycoon", "horror"],
  ["Shoot Your Nightmare The Beginning", "https://www.crazygames.com/game/shoot-your-nightmare-the-beginning", "horror"],
  ["Jeff The Killer Lost In The Nightmare", "https://www.crazygames.com/game/jeff-the-killer-lost-in-the-nightmare", "horror"],
  ["Monster Christmas Terror", "https://www.crazygames.com/game/monster-christmas-terror", "horror"],
  ["Slenderman Must Die Silent Streets", "https://www.crazygames.com/game/slenderman-must-die-silent-streets", "horror"],
  ["Slendrina Must Die The House", "https://www.crazygames.com/game/slendrina-must-die-the-house", "horror"],
  ["Slenderman Must Die Abandoned Graveyard", "https://www.crazygames.com/game/slenderman-must-die-abandoned-graveyard", "horror"],
  ["Silent House", "https://www.crazygames.com/game/silent-house", "horror"],
  ["Celestina Chapter Two", "https://www.crazygames.com/game/celestina-chapter-two", "horror"],
  ["Case Smile Horror Game Adventure", "https://www.crazygames.com/game/case-smile-horror-game-adventure", "horror"],
  ["Case Smile 2", "https://www.crazygames.com/game/case-smile-2", "horror"],
  ["Slender Clown Be Afraid Of It", "https://www.crazygames.com/game/slender-clown-be-afraid-of-it", "horror"],
  ["99 Nights Bloxd Io", "https://www.crazygames.com/game/99-nights-bloxd-io", "horror"],
  ["Mr Dude Online Multiverse Challenge", "https://www.crazygames.com/game/mr-dude-online-multiverse-challenge", "horror"],
  ["Horror Tale Kidnapper", "https://www.crazygames.com/game/horror-tale-kidnapper", "horror"],
  ["Sprunki Itn", "https://www.crazygames.com/game/sprunki-itn", "horror"],
  ["911 Prey", "https://www.crazygames.com/game/911-prey", "horror"],
  ["99 Nights Online", "https://www.crazygames.com/game/99-nights-online", "horror"],
  ["Horror Tale 3 The Witch", "https://www.crazygames.com/game/horror-tale-3-the-witch", "horror"],
  ["Antarctica 88", "https://www.crazygames.com/game/antarctica-88", "horror"],
  ["Schoolboy Escape 2", "https://www.crazygames.com/game/schoolboy-escape-2", "horror"],
  ["Kuzbass Horror", "https://www.crazygames.com/game/kuzbass-horror", "horror"],
  ["Haunted School   Horror Game", "https://www.crazygames.com/game/haunted-school---horror-game", "horror"],
  ["911 Cannibal", "https://www.crazygames.com/game/911-cannibal", "horror"],
  ["Horror Tale 2 Samantha", "https://www.crazygames.com/game/horror-tale-2-samantha", "horror"],
  ["Escape Room Strange Case 2", "https://www.crazygames.com/game/escape-room-strange-case-2", "horror"],
  ["Iron Friend", "https://www.crazygames.com/game/iron-friend", "horror"],
  ["Fnaf Shooter", "https://www.crazygames.com/game/fnaf-shooter", "horror"],
  ["Room Escape Strange Case", "https://www.crazygames.com/game/room-escape-strange-case", "horror"],
  ["Ann", "https://www.crazygames.com/game/ann", "horror"],
  ["Cornfield", "https://www.crazygames.com/game/cornfield", "horror"],
  ["Exhibit Of Sorrows", "https://www.crazygames.com/game/exhibit-of-sorrows", "horror"],
  ["Escape Portal", "https://www.crazygames.com/game/escape-portal", "horror"],
  ["Death Attraction Horror Game", "https://www.crazygames.com/game/death-attraction-horror-game", "horror"],
  ["Creepy Granny Scream Scary Freddy", "https://www.crazygames.com/game/creepy-granny-scream-scary-freddy", "horror"],
  ["Kogama Poppy Playtime", "https://www.crazygames.com/game/kogama-poppy-playtime", "horror"],
  ["Resident Zombies   Horror Shooter", "https://www.crazygames.com/game/resident-zombies---horror-shooter", "horror"],
  ["You Are Being Watched   Horror Game", "https://www.crazygames.com/game/you-are-being-watched---horror-game", "horror"],
  ["Syntaxia", "https://www.crazygames.com/game/syntaxia", "horror"],
  ["The Dawn Of Slenderman", "https://www.crazygames.com/game/the-dawn-of-slenderman", "horror"],
  ["The Owner Is Dead", "https://www.crazygames.com/game/the-owner-is-dead", "horror"],
  ["Krampus", "https://www.crazygames.com/game/krampus", "horror"],
  ["Skinwalker", "https://www.crazygames.com/game/skinwalker", "horror"],
  ["Breaking The Silent Lies", "https://www.crazygames.com/game/breaking-the-silent-lies", "horror"],
  ["Haunted School 2   Horror Game", "https://www.crazygames.com/game/haunted-school-2---horror-game", "horror"],
  ["Scary Horror Escape Room Games", "https://www.crazygames.com/game/scary-horror-escape-room-games", "horror"],
  ["Hospital Survive The Night", "https://www.crazygames.com/game/hospital-survive-the-night", "horror"],
  ["Diner In The Storm", "https://www.crazygames.com/game/diner-in-the-storm", "horror"],
  ["Evil Father", "https://www.crazygames.com/game/evil-father", "horror"],
  ["Scary Maze", "https://www.crazygames.com/game/scary-maze", "horror"],
  ["Bear Haven", "https://www.crazygames.com/game/bear-haven", "horror"],
  ["Sorcerers Refuge", "https://www.crazygames.com/game/sorcerers-refuge", "horror"],
  ["Halloween Chainsaw Massacre", "https://www.crazygames.com/game/halloween-chainsaw-massacre", "horror"],
  ["Night Watchman", "https://www.crazygames.com/game/night-watchman", "horror"],
  ["Evil Neighbor 3", "https://www.crazygames.com/game/evil-neighbor-3", "horror"],
  ["Ghost Dorm", "https://www.crazygames.com/game/ghost-dorm", "horror"],
  ["Slenderman Must Die Underground Bunker", "https://www.crazygames.com/game/slenderman-must-die-underground-bunker", "horror"],
  ["She Is Mad Eie", "https://www.crazygames.com/game/she-is-mad-eie", "horror"],
  ["Kogama Haunted Hospital", "https://www.crazygames.com/game/kogama-haunted-hospital", "horror"],
  ["Seeing Things", "https://www.crazygames.com/game/seeing-things", "horror"],
  ["Scarred", "https://www.crazygames.com/game/scarred", "horror"],
  ["Slenderman Vs Freddy The Fazbear", "https://www.crazygames.com/game/slenderman-vs-freddy-the-fazbear", "horror"],
  ["Little Cabin In The Woods A Forgotten Hill Tale", "https://www.crazygames.com/game/little-cabin-in-the-woods-a-forgotten-hill-tale", "horror"],
  ["Silent Insanity P T Psychological Trauma", "https://www.crazygames.com/game/silent-insanity-p-t-psychological-trauma", "horror"],
  ["Backwoods", "https://www.crazygames.com/game/backwoods", "horror"],
  ["Owner Is Dead 2", "https://www.crazygames.com/game/owner-is-dead-2", "horror"],
  ["House Of Celestina", "https://www.crazygames.com/game/house-of-celestina", "horror"],
  ["Shadowless Man 2", "https://www.crazygames.com/game/shadowless-man-2", "horror"],
  ["C Virus Game Outbreak", "https://www.crazygames.com/game/c-virus-game-outbreak", "horror"],
  ["Siren Head Playing In The Forest", "https://www.crazygames.com/game/siren-head-playing-in-the-forest", "horror"],
  ["Portal Of Doom Undead Rising", "https://www.crazygames.com/game/portal-of-doom-undead-rising", "horror"],
  ["The Housefly", "https://www.crazygames.com/game/the-housefly", "horror"],
  ["Dead Land Survival", "https://www.crazygames.com/game/dead-land-survival", "horror"],
  ["Nuclear Day", "https://www.crazygames.com/game/nuclear-day", "horror"],
  ["Daily Room Escape", "https://www.crazygames.com/game/daily-room-escape", "horror"],
  ["Escape From Prison Multiplayer", "https://www.crazygames.com/game/escape-from-prison-multiplayer", "horror"],
  ["Slenderman Must Die Silent Streets", "https://www.crazygames.com/game/slenderman-must-die-silent-streets", "horror"],
  ["Slendrina Must Die The Forest", "https://www.crazygames.com/game/slendrina-must-die-the-forest", "horror"],
]

// Deduplicate by URL, keeping first occurrence
const seen = new Set<string>();

// Process games and dedupe by URL
const processedGames = raw.reduce((acc, [title, url, category]) => {
  // Dedupe by URL
  if (seen.has(url)) return acc
  seen.add(url)

  acc.push({ title, url, category })
  return acc
}, [] as Game[])

// Export all games
export const games = processedGames

export const categories = [
  { id: "all", label: "All Games" },
  { id: "editors-choice", label: "Editor's Choice" },
  { id: "html", label: "HTML" },
  { id: "arcade", label: "Arcade" },
  { id: "car", label: "Car" },
  { id: "bike", label: "Bike" },
  { id: "multiplayer", label: "Multiplayer" },
  { id: "io", label: "IO" },
  { id: "od", label: "Classic" },
  { id: "atari", label: "Atari" },
  { id: "clc", label: "Clicker" },
  { id: "horror", label: "Horror" },
] as const

export function getSlug(url: string): string {
  try {
    const u = new URL(url)
    // For crazygames embed URLs, extract the slug for thumbnail
    if (u.hostname.includes("crazygames.com")) {
      return u.pathname.split("/embed/")[1] || ""
    }
    return ""
  } catch {
    return ""
  }
}

export function getThumbnail(url: string): string | null {
  // Check if it's a folder game (starts with #)
  if (url.startsWith('#')) {
    const folderName = url.substring(1) // Remove #
    console.log(`🔍 Checking for thumbnail in /games/${folderName}/thumbnail.png`)
    return `/games/${folderName}/thumbnail.png`
  }
  
  // Generate folder name from game title or URL
  const getFolderName = (url: string): string => {
    // For specific games with custom thumbnails
    if (url.includes("selenite1.freetls.fastly.net/resources/semag/gtavc")) {
      return "gta-vice-city"
    }
    if (url.includes("play2048.co")) {
      return "2048"
    }
    if (url === "https://1v1.lol" || (url.includes("1v1.lol") && !url.includes("sky-riders"))) {
      return "1v1lol"
    }
    if (url.includes("krunker.io")) {
      return "krunkerio"
    }
    if (url.includes("sky-riders-buk")) {
      return "sky-riders"
    }
    
    // For CrazyGames URLs, use the slug as folder name
    const slug = getSlug(url)
    if (slug) {
      return slug
    }
    
    // For other URLs, create a folder name from the domain
    try {
      const u = new URL(url)
      return u.hostname.replace(/[^a-z0-9]/g, '-').replace(/^-+|-+$/g, '')
    } catch {
      return "unknown"
    }
  }
  
  const folderName = getFolderName(url)
  console.log(`Checking for thumbnail in /static/games/${folderName}/thumbnail.png`)
  return `/static/games/${folderName}/thumbnail.png`
}
